HACDOCS-483: accessibility concerns
redhat-appstudio/docs.appstudio.io pull request #148
Opened 2023-06-17 03:40 UTC by missmesss

HACDOCS-483: addressing accessibility concerns in HAC docs collected by Chloe in https://docs.google.com/document/d/1TU87wilPTcimPLto38DloK6r99eo_lUxKke4hmeTcFc

2023-06-19 23:40 UTC, missmesss commented
@chloeredhat Will you please review the changes? 3 areas are addressed:

-  [Surface-level tests doc](https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/testing_applications/surface-level_tests) now has captions for tables

-  [Configuring rebuilds doc ](https://redhat-appstudio.github.io/docs.appstudio.io/Documentation/main/how-to-guides/Secure-your-supply-chain/proc_java_dependencies) now has improved links with text descriptions for them

-  There were directional indicators in both docs (under and below), they weren't particularly misleading or confusing but I tried to improve those sentences a bit just to make sure sure we eliminate any possible ambiguity. WDYT?

     1) logs for a build under the appropriate PipelineRun -> for the appropriate PipelineRun
     2) Currently implemented surface-level tests are listed below -> listed in the tables below

2023-06-19 23:42 UTC, missmesss commented
@chloeredhat This PR only addresses a11y issues, not the styling issues. I plan to look into styling as soon as I have capacity, sorry about that and thank you for reviewing all our docs.

2023-06-20 14:50 UTC, jc-berger approved these changes
/lgtm

2023-06-20 14:51 UTC, jc-berger commented
I'll let Chloe review as well since she's awesome on the a11y concerns. From my peer review, these changes look great!

2023-06-20 16:26 UTC, chloeredhat requested changes
Made a few suggestions for A11y

2023-06-20 16:26 UTC, chloeredhat commented on docs/modules/ROOT/pages/how-to-guides/Secure-your-supply-chain/proc_java_dependencies.adoc
> +The `PipelineRun` objects associated with these builds start with the build name, so you can view the logs for a build for the appropriate `PipelineRun`.
I have a few changes -- I know you didn't have time for style so some of that might be overlapping:

The names of the PipelineRun objects begin with the build name. This enables you to view logs for each PipelineRun.

2023-06-20 16:26 UTC, chloeredhat commented on docs/modules/ROOT/pages/how-to-guides/Secure-your-supply-chain/proc_java_dependencies.adoc
> +. View the logs using the command `tkn pr logs <name>`:
Either "by using" or "with" instead of just using

2023-06-20 16:26 UTC, chloeredhat commented on docs/modules/ROOT/pages/how-to-guides/Secure-your-supply-chain/proc_java_dependencies.adoc
> +The 1.11-8 release had no build file, so the project was forked and one was added. This was then added to the SCM information, see the link:https://github.com/redhat-appstudio/jvm-build-data/blob/30a
Because the 1.11-8 release had no build file, we forked the project and added a file. We then added this file to [the SCM information].

2023-06-21 01:02 UTC, missmesss commented
@chloeredhat Thanks a lot for great suggestions, I've implemented all of them. I agree, styling is an issue here too, so thanks for addressing that. I hope to get back to these guides at some point.

2023-06-21 01:22 UTC, missmesss commented
@jc-berger Thanks for being proactive and reviewing this PR already. I was going to tag you once Chloe send her suggestions in. I've pushed her feedback now. If she provides her lgtm, will you please have a  look and merge this PR please? Thanks!

2023-06-21 12:54 UTC, chloeredhat approved these changes

2023-06-21 12:54 UTC, merged