STONEBLD-1494: Add procedure to update buildah task
redhat-appstudio/docs.appstudio.io pull request #180
Opened 2023-07-24 10:45 UTC by Michkov

To unblock building applications with higher memory requirements we are providing new buildah tasks which can be used by user.

Also included commit with update of taskRef. Tekton/Openshift Pipelines are supporting multiple resolvers now, which  changed format of taskRef definition. Old way is still possible but having performace issues.

2023-07-24 11:44 UTC, gbenhaim commented
lgtm

2023-07-24 11:44 UTC, gbenhaim approved these changes

2023-07-24 15:23 UTC, gabemontero approved these changes

2023-07-24 16:36 UTC, Chr1st1anSears requested changes

2023-07-24 16:36 UTC, Chr1st1anSears commented on docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_customize_build_pipeline.adoc
> +Task `buildah` for building components from Dockerfile has a memory limit set to 4 GB. For components with higher memory requirements, there are tasks prepared:
Suggested rewrite: 
The `buildah` task, which builds components from a Dockerfile, has a memory limit of 4 GB. To build components with memory requirements greater than 4 GB, use the following tasks:

2023-07-24 16:36 UTC, Chr1st1anSears commented on docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_customize_build_pipeline.adoc
> +.. Set under `.taskRef.params` `name` to `buildah-6gb`
Suggested rewrite:
..Under `.taskRef.params`, set `name` to `buildah-6gb`.

2023-07-24 16:36 UTC, Chr1st1anSears commented on docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_customize_build_pipeline.adoc
> +.. Set under `.taskRef.params` `bundle` to `quay.io/redhat-appstudio-tekton-catalog/task-buildah-6gb:0.1`
Suggested rewrite:
..Under `.taskRef.params`, set `bundle` to `quay.io/redhat-appstudio-tekton-catalog/task-buildah-6gb:0.1`.

2023-07-24 16:36 UTC, Chr1st1anSears commented on docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_customize_build_pipeline.adoc
> +. In each `.yaml` file in the `.tekton` directory, locate a task named `build-container` under `tasks`:
Suggested rewrite:
. Go to the GitHub repo of your component.
. In each `.yaml` file in the `.tekton` directory, under `tasks`, locate the task named `build-container`:

2023-07-24 16:36 UTC, Chr1st1anSears commented on docs/modules/ROOT/pages/how-to-guides/configuring-builds/proc_customize_build_pipeline.adoc
> +
Suggested addition:
To exchange the build task with a memory limit of 6 GB, complete the following steps. For a memory limit of 8 or 10 GB, replace the references to 6 GB with the appropriate values.

2023-07-24 16:39 UTC, Chr1st1anSears commented
Hey @Michkov--thanks for your PR and for requesting my review! I appreciate the helpful updates you've provided to the technical details of our doc. However, to ensure that the doc complies with our best practices as writers, I've requested a number of changes. Please let me know if you have any questions about them.

2023-07-26 06:20 UTC, Michkov commented
@Chr1st1anSears thanks for review. Document updated.

BTW github provides ability to directly propose the changes of the code. Then I would be able to just accept your suggestions ;-).
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-comments-to-a-pull-request - point 6

2023-07-26 14:31 UTC, Chr1st1anSears commented
@Michkov looks good and you're right lol that would definitely be a better way to leave a review next time. Thanks for pointing that out.

2023-07-26 14:31 UTC, Chr1st1anSears approved these changes

2023-07-26 14:31 UTC, merged