Update proc_inspect-slsa-provenance.adoc
redhat-appstudio/docs.appstudio.io pull request #207
Opened 2023-10-19 18:47 UTC by Roming22

Add details about the Tekton Chains public-key.
The information is needed for users to verify the SLSA provenance

2023-10-19 19:46 UTC, ralphbean approved these changes

2023-10-19 20:12 UTC, Roming22 commented
Tagging @Chr1st1anSears since they seem to be in charge of merge :wink:

2023-10-20 14:23 UTC, Chr1st1anSears requested changes

2023-10-20 14:46 UTC, Roming22 commented on docs/modules/ROOT/pages/how-to-guides/Secure-your-supply-chain/proc_inspect-slsa-provenance.adoc
> +* Red Hat's Enterprise Contract (EC) is a powerful tool that you can also use to verify your SLSA provenance; visit link:https://enterprisecontract.dev/posts/introducing-the-enterprise-contract/[this
Done

2023-10-20 14:47 UTC, Roming22 commented
@Chr1st1anSears PR updated.

2023-10-20 14:48 UTC, Chr1st1anSears approved these changes

2023-10-20 14:49 UTC, Chr1st1anSears commented
Thanks for your PR @Roming22--merging now :+1:

2023-10-20 14:49 UTC, merged